name: npm-publish
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - 'package.json'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'
      - name: install
        run: npm install
      - run: npm run test
      - name: Authenticate with npm
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.ADOBE_BOT_NPM_TOKEN }}" > .npmrc
          git update-index --skip-worktree .npmrc
      - name: Publish to npm
        run: npm publish --access public
